### ISSUE TITLE
Getting error message 'ProgressBar Addin isn't a valid add-in'

### ISSUE THREAD

**Issue by rajivvishwa** [utopiaplanetia/ppt-progress-bar#1]
Tried the steps you have mentioned but I get the error 
`ProgressBar Addin isn't a valid add-in`

Check the screenshots below,

![2014-03-11 12_02_28-add new powerpoint add-in](https://f.cloud.github.com/assets/125708/2389624/35b13ece-a950-11e3-9e3c-f497aec43bf7.png)

![2014-03-11 12_02_40-presentation1 - microsoft powerpoint](https://f.cloud.github.com/assets/125708/2389626/382e7ff4-a950-11e3-9a5f-d48cc42a350a.png)

**Comment by utopiaplanetia** [comment]
Check out the latest version of the addin and retry :)
